# local: 	http://localhost:8501
# prd: 		http://ifinanceapp.streamlit.app/

[auth]
redirect_uri="http://ifinanceapp.streamlit.app/oauth2callback"
cookie_secret="rC5V0RZd2Pg3OxoavsaYBYogdRsjS1ZI"

[auth.google]
client_id="386934443732-meigds0b567uhllb1qmt49id3p52s5tt.apps.googleusercontent.com"
client_secret="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"
server_metadata_url="https://accounts.google.com/.well-known/openid-configuration"